### ISSUE TITLE
Getting error while making interfaces up or down using module dellemc.enterprise_sonic.sonic_interfaces:  {"changed": false, "code": -32603, "msg": "'command'"}

### ISSUE THREAD

**Issue by shoneslab** [ansible-collections/dellemc.enterprise_sonic#397] opened 2024-06-14 16:52 UTC
### Bug Description

I am trying make the sonic ethernet interfaces interfaces up/down using the module and getting the error:

Playbook
```
---
- name: Manage Sonic Switch Interfaces
  hosts: vault_cleanroom_switches
  gather_facts: no
  collections:
    - dellemc.enterprise_sonic

  tasks:
     - name: Set interface down
      dellemc.enterprise_sonic.sonic_interfaces:
        config:
          - name: Ethernet12
            enabled: True
        state: replaced
```

Inventory File

```
all:
  children:
    vault_cleanroom_switches:
      hosts:
        sonic_switch_01:
          ansible_host: 192.168.60.2
          ansible_user: admin
          ansible_password: YourPaSsWoRd
          ansible_connection: network_cli
          ansible_network_os: dellemc.enterprise_sonic.sonic
```

### Product Name

Dell Enterprise Sonic Ansible Module

### Component or Module Name

dellemc.enterprise_sonic.sonic_interfaces

### DellEMC Enterprise SONiC Ansible Collection Version

v2.4.0

### SONiC Software Version

Enterprise Sonic 4.2.1 on GNS3 2.2.47

### Configuration

**ansible version**
```
ansible [core 2.17.0]
  config file = /opt/automation/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections:/opt/automation/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 18 2024, 07:52:31) [GCC 13.2.1 20240309] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Steps to Reproduce

Execute the playbook.

### Expected Behavior

Playbook should exit successfully by making the interface enabled with status up

### Actual Behavior

```
TASK [Set interface down] ****************************************************************************************************************************************
fatal: [sonic_switch_01]: FAILED! => {"changed": false, "code": -32603, "msg": "'command'"}

```

### Logs

```
ansible-playbook -i inventory/ playbooks/airgap-management.yml 

PLAY [Manage Sonic Switch Interfaces] ****************************************************************************************************************************

TASK [Set interface down] ****************************************************************************************************************************************
fatal: [sonic_switch_01]: FAILED! => {"changed": false, "code": -32603, "msg": "'command'"}

PLAY RECAP *******************************************************************************************************************************************************
sonic_switch_01            : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

**Comment by kerry-meyer** [comment] 2024-06-17 17:39
Hi Shone,

Please send the output from running the failing playbook in 'verbose' mode.

e.g.

ansible-playbook -i <inventory file path> <playbook path> -vvvv

                                  Kerry Meyer

**Comment by shoneslab** [comment] 2024-06-18 18:05
TASK [Set interface down] **************************************************************************************************************************************
task path: /opt/automation/playbooks/airgap-management.yml:25
redirecting (type: action) dellemc.enterprise_sonic.sonic_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: action) dellemc.enterprise_sonic.sonic_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_interfaces to dellemc.enterprise_sonic.sonic
redirecting (type: action) dellemc.enterprise_sonic.sonic_interfaces to dellemc.enterprise_sonic.sonic
The full traceback is:
  File "/opt/automation/collections/ansible_collections/dellemc/enterprise_sonic/plugins/module_utils/network/sonic/facts/interfaces/interfaces.py", line 55, in get_all_interfaces
    response = edit_config(self._module, to_request(self._module, request))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/automation/collections/ansible_collections/dellemc/enterprise_sonic/plugins/module_utils/network/sonic/sonic.py", line 139, in edit_config
    return connection.edit_config(commands)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ansible/module_utils/connection.py", line 199, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [sonic_switch_01]: FAILED! => {
    "changed": false,
    "code": -32603,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "advertised_speed": null,
                    "auto_negotiate": null,
                    "description": null,
                    "enabled": true,
                    "fec": null,
                    "mtu": null,
                    "name": "Ethernet12",
                    "speed": null
                }
            ],
            "state": "replaced"
        }
    },
    "msg": "'command'"
}
The full traceback is:
  File "/opt/automation/collections/ansible_collections/dellemc/enterprise_sonic/plugins/module_utils/network/sonic/facts/interfaces/interfaces.py", line 55, in get_all_interfaces
    response = edit_config(self._module, to_request(self._module, request))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/automation/collections/ansible_collections/dellemc/enterprise_sonic/plugins/module_utils/network/sonic/sonic.py", line 139, in edit_config
    return connection.edit_config(commands)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ansible/module_utils/connection.py", line 199, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [sonic_switch_02]: FAILED! => {
    "changed": false,
    "code": -32603,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "advertised_speed": null,
                    "auto_negotiate": null,
                    "description": null,
                    "enabled": true,
                    "fec": null,
                    "mtu": null,
                    "name": "Ethernet12",
                    "speed": null
                }
            ],
            "state": "replaced"
        }
    },
    "msg": "'command'"
}

**Comment by kerry-meyer** [comment] 2024-06-19 22:34
The following two corrections are required for this playbook to make it work as intended:

- Override the inventory default connection type of 'network_cli' to use 'httpapi' instead. (The 'httpapi' connection type is required for sending REST APIs to a device via our standard non-cli resource modules. These resource modules take yaml input from playbook tasks instead of CLI and send the corresponding REST APIs via https protocol.)
- Adjust the indentation of the resource module name under the "-name ..." statement in the task. (Also, since the resource module collection name has already been specified at the top, it is not needed again when specifying the module to be used.)
- Recommended but not required: Indent the remaining lines by one more space so the block is indented by two spaces instead of one.

The resulting revised playbook would look like this:

(Changed and added lines are marked by '<<<' to annotate them.)

```
---
- name: Manage Sonic Switch Interfaces
  hosts: vault_cleanroom_switches
  gather_facts: no
  connection: httpapi                           <<<  (Add this.)
  collections:
    - dellemc.enterprise_sonic

  tasks:
     - name: Set interface down
        sonic_interfaces:                          <<< correct indentation; shorten to module name
          config:                                       <<< recommended: indent these remaining lines by one more space
          - name: Ethernet12
            enabled: True
          state: replaced
```

**Comment by kerry-meyer** [comment] 2024-06-20 19:15
I am closing this issue because the playbook that generated the problem symptoms had problems in the YAML syntax. With a revised version of an equivalent playbook, the operation executes successfully using the current released version of the Dell enterprise_sonic Ansible resource module collection.

**Closed by kerry-meyer** 2024-06-20 19:15 UTC
