### ISSUE TITLE
[BUG]: Removing an interface from Vrf is removing all other interfaces

### ISSUE THREAD

**Issue by kannankvs** [ansible-collections/dellemc.enterprise_sonic#194] opened 2023-03-27 18:33 UTC
### Bug Description

Deletion of one interface from the VRF is deleting all the interfaces.

** CONFIG BEFORE RUNNING PLAYBOOK: ** 
z9432f-12003# show ip vrf
VRF-NAME            INTERFACES
VrfReg1             Eth1/11
                    Eth1/12
                    Eth1/13
default

** PLAYBOOK TO DELETE ETH1/12 from VrfReg1 **
---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: Configuring vrf deleted state
      dellemc.enterprise_sonic.sonic_vrfs:
        config:
         - name: VrfReg1
           members:
             interfaces:
               - name: Eth1/12
        state: deleted

** Show after executing the playbook ** 
z9432f-12003# show ip vrf
VRF-NAME            INTERFACES
VrfReg1
default
z9432f-12003#

### Product Name

eSONiC Collections

### Component or Module Name

vrfs

### DellEMC Enterprise SONiC Ansible Collection Version

2.0

### SONiC Software Version

eSONiC 4.04

### Configuration

z9432f-12003# configure terminal
z9432f-12003(config)# ip vrf VrfReg1
z9432f-12003(config)#
z9432f-12003(config)# interface Eth 1/11
z9432f-12003(config-if-Eth1/11)# ip vrf forwarding VrfReg1
z9432f-12003(config-if-Eth1/11)# interface Eth 1/12
z9432f-12003(config-if-Eth1/12)# ip vrf forwarding VrfReg1
z9432f-12003(config-if-Eth1/12)# interface Eth 1/13
z9432f-12003(config-if-Eth1/13)# ip vrf forwarding VrfReg1
z9432f-12003(config-if-Eth1/13)#
z9432f-12003(config-if-Eth1/13)#
z9432f-12003(config-if-Eth1/13)# end
z9432f-12003# show ip vrf
VRF-NAME            INTERFACES
----------------------------------------------------------------
VrfReg1             Eth1/11
                    Eth1/12
                    Eth1/13
default

### Steps to Reproduce

---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: Configuring vrf deleted state
      dellemc.enterprise_sonic.sonic_vrfs:
        config:
         - name: VrfReg1
           members:
             interfaces:
               - name: Eth1/12
        state: deleted

### Expected Behavior

Should delete only Eth1/12.

### Actual Behavior

Its deleting all the 3 interfaces from VrfReg1

### Logs

z9432f-12003# show ip vrf
VRF-NAME            INTERFACES
----------------------------------------------------------------
VrfReg1
default
z9432f-12003#

**Comment by kannankvs** [comment] 2023-03-27 18:36
Suspecting the bug in the file, plugins/module_utils/network/sonic/config/vrfs/vrfs.py, function get_delete_vrf_interface_requests.

The line "matched = next((have_cfg for have_cfg in have if have_cfg['name'] == name), None)" is trying to get the matching names; but this match is only for VrfName. Its not comparing the interface names one by one. 

When the above line is deleted and when the following code (just a crooked way to debug, I added this code; this code would require fine tuning before finalizing), it works as expected.
            matched = {}
            matched_members = {}
            matched_intf = []
            for have_cfg in have:
                print("\n KVSK: have_cfg = ", have_cfg)
                print("\n KVSK: name = ", name)
                print("\n KVSK: have_cfg['name'] = ", have_cfg['name'])
                if have_cfg['name'] == name:
                    print("\n KVSK: have_cfg['name']  ane name matches")
                    for intf in have_cfg['members']['interfaces']:
                        print("\n KVSK: FOR: intf in have_cfg['members']['interfaces']", intf)
                        for del1 in interfaces:
                            print("\n KVSK: FOR: del1 in interfaces", del1)
                            if del1 == intf:
                                del_mem = del1
                                matched_intf.append (del_mem)
                                print("\n KVSK: adding matching intf to list = ", matched_intf)
            matched_members['interfaces'] = matched_intf
            matched['members'] = matched_members

**Comment by mingjunzhang2019** [comment] 2023-04-06 21:28
mingjunzhang2019 is working on this issue

**Comment by mingjunzhang2019** [comment] 2023-04-10 17:58
The issue is fixed with the above listed PR.

**Comment by kannankvs** [comment] 2023-04-11 16:10
The PR230 mentioned above is not yet merged. Requesting the bug owner to keep the bug as open until the PR is merged.

**Comment by kerry-meyer** [comment] 2023-04-20 05:44
The PR has been merged. I am closing the bug. The UT enclosure demonstrates that with this fix the deletion operation is working as intended.

**Comment by kerry-meyer** [comment] 2023-04-20 05:46
The PR has been merged. I am closing the bug. The UT enclosure demonstrates that with this fix the deletion operation is working as intended.

**Closed** 2023-04-20 05:45 UTC
